# Every property used in resource templates must also be added to the
# expandProps map in buildSrc/src/main/groovy/multiloader-common.gradle.

# Project
version=0.3.0
group=fr.tidic.jeichaincraft
java_version=25

# Common
minecraft_version=26.2
minecraft_version_range=[26.2,26.3)
mod_name=JEI Chain Craft
mod_author=Tidic
mod_id=jeichaincraft
license=MIT
description=Recursive crafting tree visualization for JEI.
# https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.2-2

# Fabric — https://fabricmc.net/develop/
fabric_version=0.160.0+26.2
fabric_loader_version=0.19.5

# NeoForge — https://projects.neoforged.net/neoforged/neoforge
neoforge_version=26.2.0.88
neoforge_loader_version_range=[4,)

# JEI — https://maven.blamejared.com/mezz/jei/
jei_version=30.32.0.221
jei_mc_version=26.2

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
