# Every property used in resource templates must also be added to the
# expandProps map in buildSrc/src/main/groovy/multiloader-common.gradle.

# Project
version=0.3.0
group=fr.tidic.jeichaincraft
java_version=21

# Common
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
mod_name=JEI Chain Craft
mod_author=Tidic
mod_id=jeichaincraft
license=MIT
description=Recursive crafting tree visualization for JEI.
# https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.1-20240808.144430
# https://parchmentmc.org/docs/getting-started
parchment_minecraft=1.21.1
parchment_version=2024.11.17

# Fabric — https://fabricmc.net/develop/
fabric_version=0.116.17+1.21.1
fabric_loader_version=0.19.5

# NeoForge — https://projects.neoforged.net/neoforged/neoforge
neoforge_version=21.1.228
neoforge_loader_version_range=[4,)

# JEI — https://maven.blamejared.com/mezz/jei/
jei_version=19.27.0.340
jei_mc_version=1.21.1

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
